---
 
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Amazon Linux)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      #update_only: yes # not supported by apt
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Amazon Linux servers
    tags: apache,httpd,amazon
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
