- name: install apache and php packages
  tags: apache,httpd,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

# just an example for lineinfile
- name: change e-mail address for admin (Amazon Linux)
  tags: apache,httpd,amazon
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Amazon"
  register: apache

- name: restart httpd
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: restarted
  # attention: if the `register: apache` was initiated in another play,
  # without making a change, this condition would not register as `changed`
  when: apache.changed

- name: copy default html file for site
  tags: apache,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
