#- name: key management
#  tags: always
#  authorized_key:
#    user: someone
#    key: "public ssh-key"
#    #state: absent

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
